version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run: gcloud version
      - run: echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file gcloud-service-key.json
      - run: gcloud config set project $PROJECT_ID
      - run: gsutil -m rsync -c -d -r -x '.*/.*\.html$|.git.*$|.*.md$|.*.sh$' . gs://marki-test/tiles
      - run: gsutil -m setmeta -r -h cache-control:no-cache gs://marki-test/tiles
      - run: gsutil -m acl ch -u AllUsers:R -r gs://marki-test/tiles
