version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run: gcloud version
      - run: gcloud config configurations list
      - run: gcloud auth activate-service-account --key-file sc-neptune-dev-238c62c70599.json
      - run: gcloud config configurations list
      - run: gcloud config set project sc-neptune-dev
      - run: gcloud config configurations list
      - run: gsutil ls
      - run: gsutil ls gs://marki-test/
