version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run: gcloud version
      - run: echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file gcloud-service-key.json
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud config configurations list
      - run: echo $PROJECT_NAME
